# Generated by Django 5.2 on 2025-05-01 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='madia')),
                ('dec', models.TextField()),
                ('price', models.IntegerField()),
                ('cate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
