# Generated by Django 5.2 on 2025-05-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_ad_to_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ad_to_cart',
            new_name='Add_to_cart',
        ),
    ]
