# Generated by Django 5.2 on 2025-05-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_ad_to_cart_add_to_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Our_Product',
        ),
    ]
