# Generated by Django 5.2 on 2025-05-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_add_to_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('company_name', models.TextField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.TextField(max_length=50)),
                ('contry', models.TextField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('note', models.TextField()),
            ],
        ),
    ]
