# Generated by Django 5.2 on 2025-05-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_billing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='contry',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
