# Generated by Django 5.2 on 2025-05-22 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_billing_details_contry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_details',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
