# Generated by Django 5.2 on 2025-05-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
