# Generated by Django 5.2 on 2025-06-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_order_coupon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_id',
        ),
    ]
